version: '3'

services:
  database:
    image: mongo
    container_name: mongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=DB
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'

  server:
    image: lalogg/p1_sopes1_p14_bk:7.0.0
    container_name: server_container
    # environment:
    #   - DB_HOST:${DB_HOST}
    #   - DB_PORT:${DB_PORT}
    #   - DB_NAME:${DB_NAME}
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: /proc
        target: /proc
    command: /bin/bash -c "apt-get update && apt-get install -y sysstat && ./main"
    restart: always
    depends_on:
      - database
    links:
      - database

  client:
    image: lalogg/p1_sopes1_p14_ftnd:14.0.0
    container_name: client_container
    ports:
      - '80:80'
    restart: always
    depends_on:
      - server
    links:
      - server

volumes:
  mongo-data:
    external: false
    


